compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

checksumBehavior: update

npmScopes:
  amzn:
    npmAlwaysAuth: true
    npmAuthToken: ***REMOVED-JFROG-TOKEN***
    npmRegistryServer: "https://registry.npmjs.org/"
