export const EventSource = Object.freeze({
    NONE: "com.adobe.eventSource.none",
    OS: "com.adobe.eventSource.os",
    REQUEST_CONTENT: "com.adobe.eventSource.requestContent",
    REQUEST_IDENTITY: "com.adobe.eventSource.requestIdentity",
    REQUEST_RESET: "com.adobe.eventSource.requestReset",
    RESPONSE_CONTENT: "com.adobe.eventSource.responseContent",
    RESPONSE_IDENTITY: "com.adobe.eventSource.responseIdentity",
    SHARED_STATE: "com.adobe.eventSource.sharedState",
    WILDCARD: "com.adobe.eventSource._wildcard_",
    APPLICATION_LAUNCH: "com.adobe.eventSource.applicationLaunch",
    APPLICATION_CLOSE: "com.adobe.eventSource.applicationClose",
    CONSENT_PREFERENCE: "consent:preferences",
    UPDATE_CONSENT: "com.adobe.eventSource.updateConsent",
    RESET_COMPLETE: "com.adobe.eventSource.resetComplete",
    UPDATE_IDENTITY: "com.adobe.eventSource.updateIdentity",
    REMOVE_IDENTITY: "com.adobe.eventSource.removeIdentity",
    ERROR_RESPONSE_CONTENT: "com.adobe.eventSource.errorResponseContent",
    CREATE_TRACKER: "com.adobe.eventSource.createTracker",
    TRACK_MEDIA: "com.adobe.eventSource.trackMedia",
    CONTENT_COMPLETE: "com.adobe.eventSource.contentComplete",
});